version: '3.9'

services:
    gsw:
        container_name: gsw
        image: gsw
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./src:/root/project/src
            - ./public:/root/project/public
